# Generated by Django 4.2 on 2023-06-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('salary', models.FloatField(default=1200)),
                ('phone', models.PositiveIntegerField(unique=True)),
                ('charge', models.CharField(max_length=100)),
            ],
        ),
    ]
